R/visualize_species_per_deployment.R
man/visualize_species_per_deployment.Rd
vignettes/visualize-number-of-species-per-deployment.Rmd

This PR should solve #5 by providing number of species as default option for arg `hover_column`.
Function, documentation and vignette updated.

Add n species to hovering

---

R/get_effort.R
R/map_dep.R
R/zzz.R
man/get_effort.Rd
tests/testthat/test-get_effort.R
vignettes/visualize-deployment-features.Rmd

This PR solves #24 
Also it does:
1. add unit-tests for `get_effort()`
2. improve informative message when wrong `effort_unit` value is passed to the function, by adding `NULL` to the list of possible values, e.g.
```r
> get_effort(camtrapdp, unit = "bad")
Error: Invalid value for unit argument.
Valid inputs are: NULL, second, minute, hour, day, month and year. 
```
This small improvement applies to other functions where NULL is a possible value of an argument, e.g. `species` argument of `get_n_obs()` function:
```r
> get_n_obs(camtrapdp, species = "bad!")
Error: Invalid value for species argument.
Valid inputs are: NULL, anas platyrhynchos, rattus norvegicus, ondatra zibethicus, myocastor coypus, gallinula chloropus, mallard, norway rat, muskrat, coypu and common moorhen. 
```

Add time unit get effort

---

DESCRIPTION
R/filter_predicates.R
R/get_effort.R
tests/testthat/test-filter_predicates.R
tests/testthat/test-get_effort.R

Apply defensive programming strategy even in `get_effort()` and `apply_filter_predicate()` functions by better checking the input of these two functions.

Improve input checks

---

DESCRIPTION
R/read_camtrap_dp.R
tests/testthat/test-read_camtrap_dp.R

Small PR to follow switch of args in `datapackage::read_resource()`, see https://github.com/inbo/datapackage/pull/36

Switch resourcename package

---

DESCRIPTION
R/read_camtrap_dp.R

This reverts https://github.com/inbo/camtrapdp/commit/33ec61043f0aaff7099bf1ff7bc53b0a8b4600dd to reflect the change in `frictionless` package (see https://github.com/frictionlessdata/frictionless-r/issues/53).

Switch back resource name and package

---

DESCRIPTION
R/map_dep.R
man/map_dep.Rd
tests/testthat/test-transform_effort_to_common_units.R
vignettes/visualize-deployment-features.Rmd

This PR implements the ideas I proposed for #34. 
Argument `palette` added to `map_dep()`. By deafult palette `inferno` is used (see example in https://github.com/inbo/camtrapdp/issues/34#issuecomment-1010077740). This palette starts with black for value 0, so it satisfies the need described in #34.
Documentation of `map_dep()` and [vignette](https://github.com/inbo/camtrapdp/blob/main/vignettes/visualize-deployment-features.Rmd) adapted.

Color palette for map_dep()

---

R/map_dep.R
vignettes/visualize-deployment-features.Rmd

This PR improves visualization of deployments where feature to visualize is equal to 0. Gray markers are added.
Examples:

Add markers for 0 values

---

R/map_dep.R
man/map_dep.Rd
vignettes/visualize-deployment-features.Rmd

Based on preference of @jimcasaer in https://github.com/inbo/camtrapdp/issues/34#issuecomment-1058432051, this PR:
1. Adds argument `zero_values_color` to `map_dep()` function with deafult value `"red"` (deafult `fillOpacity` and `opacity` used, i.e. 0.5)
2. Updates documentation of `map_dep()`
3. Adds section about use of `zero_values_color` in vignette [visualize-deployment-features.Rmd](https://github.com/inbo/camtrapdp/blob/special-color-zeros/vignettes/visualize-deployment-features.Rmd)

Improve visualization of deploys with zero value

---

DESCRIPTION
R/map_dep.R
vignettes/visualize-deployment-features.Rmd

Layer with non zero values deployments allows clustering as well (default). Argument `cluster` works on both layers (non zero and zero deploys).
Vignette visualization improved as well: removed typo and old reference to the "ugly" big markers.

Add clustering of non zero values

---

R/map_dep.R

This very small PR inverts the orders of the layers visualizing the deployments with non-zero values and the ones with zero values as agreed with @jimcasaer in https://github.com/inbo/camtrapdp/issues/34#issuecomment-1065016236.

Invert orders layers zero and non-zero values

---

R/map_dep.R
man/map_dep.Rd
vignettes/visualize-deployment-features.Rmd

This PR solves #34 by using icons for deploys with zero values. 
Args added:
- `zero_values_show`: `TRUE` (default) or `FALSE`
- `zero_Values_icon_url`: an URL to an icon. Default, the multiply symbol `x` as in [`"https://img.icons8.com/ios-glyphs/30/000000/multiply.png"`](https://img.icons8.com/ios-glyphs/30/000000/multiply.png).
- `zero_values_icon_size`: number of pixels. Default: 10.
This PR fixes also a bug and improves documentation while passing a vector of colors to `palette` argument.

Zero as icons

---

DESCRIPTION
R/read_camtrap_dp.R
man/read_camtrap_dp.Rd

- Rename variable in example to camtrap_dp_file rather than _dir (which was the old behaviour)
- Use system.file() rather than here() to get file
- Drop here dependency
The advantage of not using `here` is that you won't have name clashes with the `here()` function loaded from lubridate.

Remove `here`, update read_camtrap_dp example

---

R/get_cam_op.R
tests/testthat/test-get_cam_op.R

This PR solves #110 which is caused by a bug in camera operation matrix at first tackled at #104 based on issue #99.
The previous solution worked well for one to one relationship locations-deployments or in cases when deployments activity intervals were not disjointed (not simultaneously active), but introduced NAs when a location was linked to deploymenst active at different moments.
Some tests were added to fully check the situation with multiple deployments per location.

Multiple deployments, same location: remove bugs camera operation matrix

---

R/write_dwc.R
R/write_eml.R
inst/sql/dwc_occurrence.sql
man/write_dwc.Rd
man/write_eml.Rd

EML now makes use of `package$coordinatePrecision` to state:
> Geospatial coordinates are provided as is.
or
> Geospatial coordinates are as rounded to {0.001} degrees
Darwin Core now make use of `package$coordinatePrecision` to add:
- dataGeneralizations: "coordinates rounded to {0.001} degrees" (or NULL)
- coordinatePrecision: 0.001 (or NULL)
Ping @tucotuco

Document rounded coordinates in EML / DwC

---

inst/sql/dwc_audubon.sql
inst/sql/dwc_occurrence.sql

- Drop `locationRemarks` (was used for featureType, but that is better expressed in `eventRemarks`)
- Create `eventRemarks` as:
```
camera trap with food bait near carcass | tags: boven de stroom | van 29/07/2020 tot 08/08/2020 120 foto's
camera trap without bait near other feature
camera trap
```
- Set `samplingProtocol` to fixed value `camera trap` (rather than `camera trap`, `camera trap with bait`, `camera trap without bait`) for easier searching in GBIF. Cf. `gps` for Movebank datasets.
fyi @tucotuco

Fix #131: eventRemarks + use fixed `camera trap` for samplingProtocol

---

.gitignore
DESCRIPTION
R/read_camtrap_dp.R
camtraptor.Rproj
tests/testthat/test-read_camtrap_dp.R

This PR solves #185 and #182.
I have been quite conservative in solving #185 to avoid errors in case of renaming non-existing columns.
I do not trigger any warning but I inform the user about non standard fields by returning three messages on console:
```r
Non standard field after _id found: renamed to speed.                                                                 
Non standard field after _id found: renamed to radius.
Non standard field after _id found: renamed to angle.
```

Add non standard fields

---

DESCRIPTION
R/check_species.R
R/get_cam_op.R
R/get_custom_effort.R
R/get_effort.R
R/get_n_individuals.R
R/get_n_obs.R
R/get_n_species.R
R/get_record_table.R
R/read_camtrap_dp.R
tests/testthat/test-calc_animal_pos.R
tests/testthat/test-get_record_table.R

This PR aims to follow the changes in dplyr 1.1.0.
1. 777e12b6c05bc3fa8e34a1ac648f34bb06406e10: do not use `dplyr::na_if()` for replacing 0 with NA over all the data.frame (see bullet point referring to this function in https://dplyr.tidyverse.org/news/index.html#vctrs-1-1-0 and https://github.com/tidyverse/dplyr/issues/6329)
2. 8f1c2bf57698679bf250136a9a2448a3051f9e91: do not use `.data` in tidyselect expressions (`select()`, `rename()`, `relocate()`) as it generates warnings. Use `"colname"` syntax instead. In this way no notes about "no visible binding for global variable" arise. See https://dplyr.tidyverse.org/articles/programming.html#eliminating-r-cmd-check-notes. 
3. 8f1c2bf57698679bf250136a9a2448a3051f9e91 (same commit as 2): add `multiple = "all"` in a `left_join()` to avoid …

Upgrade package based on dplyr 1.1.0 release

---

R/get_effort.R
R/get_record_table.R
vignettes/filter-predicates.Rmd
vignettes/record-table.Rmd
vignettes/visualize-deployment-features.Rmd

I made some minor spelling corrections, checked via `spelling::spell_check_package()`

Minor spelling corrections

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

This small PR:
- avoids automatic checks actions will run on drafts
- allows them to be run on demand

Improve trigger actions

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

PR #227 didn't work as wished: commits of an open PR ready for review didn't trigger the automatic checks. Only the switch from draft to PR triggered such checks, which is not enough.
Solution here implemented comes from this GitHub discussion comment: https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
It seems also that the workflow dispatch trigger works, i.e. the `if: github.event.pull_request.draft == false` in the jobs doesn't skip the action when it is manually triggered. I have just checked by triggering the R-CMD-check action on this PR with status draft, see https://github.com/inbo/camtraptor/actions/runs/5543168228/workflow

Trigger checks after each commit PR ready for review

---

R/write_eml.R
man/get_effort.Rd
man/get_record_table.Rd
tests/testthat/_snaps/write_eml.md

Fixes #160
I changed a single character in `write_eml()`, and updated the snapshots. When updating the documentation: 7edcee01d34314a132c52c96ce47d7c74afeea4c, `get_effort.Rd` and `get_effort_table.Rd` updated.

Write orcids as https in `write_eml()`

---

tests/testthat/test-check_package.R
vignettes/visualize-deployment-features.Rmd

Typos are everywhere, it seems. This small PR is just an attempt to remove one of them and improve a sentence as well. Nothing more than that.

Remove small typo and improve sentence

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
README.Rmd
README.md
man/apply_filter_predicate.Rd

Fixes #268
Using the [`NEWS.md` from frictionless](https://github.com/frictionlessdata/frictionless-r/blob/main/NEWS.md) as inspiration, I've added a NEWS.md with items from #244 and #207. I used `usethis::use_news_md()`.
I suggest we update `NEWS.md` iteratively as we bring more changes to the v1.0 branch.

268 add news.md

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
R/get_custom_effort.R
man/get_custom_effort.Rd
tests/testthat/test-get_custom_effort.R

This PR solves #219 by using calendar weeks/months/years for grouping while calculating the effort.
Unit-tests in `test-get_custom_effort()` have been not only updated, but also sensibly improved partly based on testthat things learned while working on #272 thanks to @PietrH.

Use calendar values in `get_custom_effort`

---

NEWS.md
R/get_cam_op.R
R/get_record_table.R
man/get_cam_op.Rd
man/get_record_table.Rd
tests/testthat/test-calc_animal_pos.R
tests/testthat/test-check_species.R
tests/testthat/test-get_cam_op.R
tests/testthat/test-get_effort.R
tests/testthat/test-get_record_table.R
vignettes/camera-operation-matrix.Rmd
vignettes/record-table.Rmd

This PR solves:
- #279
- #288
Also, some examples of `get_record_table` have been updated as the last version of `mica` datapackage we are using do not contain observations made in quick succession. Same holds true for the correspondent unit-tests.

Fix 288 and 279

---

DESCRIPTION
NEWS.md
R/write_eml.R
R/zzz.R

This PR fixes two issues I encountered when running `write_eml()` on a Camtrap DP 1.0 version of the entire MICA dataset.
1. Conversion: move the entire first of `package$sources` to `package$platform`: `write_eml()` couldn't find `platform$path` before because only the title was copied.
2. Use a simpler way to arrange the contributors on a provided order of names. It errored before.
3. Always choose taxonID from taxonomy if available

Fix two `write_eml()` issues

---

DESCRIPTION
R/zzz.R
tests/testthat/test-read_camtrap_dp.R

This PR fixes #291.
During conversion to older version, it takes for each `eventID`-`individualID` the values of `individualPositionRadius` and `individualPositionAngle` where the following holds true:
- `individualPositionRadius` and `individualPositionAngle` are both not NA
- `eventStart` is the lowest one. In case of multiple values with same `eventStart`, the first row is taken (this is more a safety move, as using `individualID` for grouping there shouldn't be multiple values of `eventStart` for each group)
This results in one and only one value of `individualPositionRadius` and `individualPositionAngle` for each `eventID`-`individualID`.
These values are joint to event-based observations based on `eventID`-`individualID`.

Add radius and angle to event-based observations

---

DESCRIPTION
NEWS.md
R/get_custom_effort.R
man/get_custom_effort.Rd
tests/testthat/test-get_custom_effort.R

This PR will solve #333.
Thanks @MartijnUH for the very well description of the requested feature and the code.
I think I adapted `get_custom_effort` as you wished.
Test it hard please 🔨 
Can you please test the PR and so review it? Thanks.
You can install this PR directly in R:
```r
devtools::install_github("inbo/camtraptor", ref = "pull/335/head")
```
Notice that in the example on how to calculate the total effort over all deployments (added as example in function documentation), I needed to add **`dplyr::filter(effort > 0)`** to your provided code, otherwise I get all deployments in `deploymentIDs`, `ndep` and `nloc`:
```r
get_custom_effort(mica, group_by = "year", unit = "day") %>%
dplyr::filter(effort > 0) %>%
dplyr::group_by(begin) %>% 
dplyr::summarise(
deploymentIDs = …
```

Adapt `get_custom_effort`

---

.github/workflows/test-coverage.yaml

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Closes #347 
> Starting December 5, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible. While v4 of the artifact actions improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require updates to your …

Switch to artifacts v4

---

DESCRIPTION
NEWS.md
R/get_record_table.R
R/zzz.R
tests/testthat/test-get_record_table.R

This pull request includes several updates to the `camtraptor` package, primarily focusing on adding new columns to the `get_record_table()` output (see #341), updating the package version, and adding new tests to ensure the correctness of the new functionality.
* `get_record_table()` now returns four new columns: `longitude`, `latitude`, `clock` (clock time in radians), and `solar` (solar time in radians).
* Updated the package version from 0.26.0 to 0.27.0 in the `DESCRIPTION` file.
* Added `activity` (for `getTime()` used for `clock` column) and `overlap` (for `sunTime()` used for `solar` column) to the `Imports` section in the `DESCRIPTION` file.
* Introduced a new helper function `add_coordinates()` to add deployment coordinates to observations based on `deploymentID`.
* Added tests …

Add clock sun record table
